module.exports = {
  SaplingLogo: require('./sapling-logo.png'),
  ProWritingAidLogo: require('./pro-writing-aid-logo.png'),
  Airplane: require('./airplane.png'),
  Baseball: require('./baseball.png'),
  GraduationSpeech: require('./graduationSpeech.png'),
  Grind: require('./grind.png'),
  Loading: require('./loading.gif'),
  LoadingWhite: require('./loading-white.gif'),
  Logo: require('./logo.png'),
  Notification: require('./notification.png'),
  Office: require('./office.png'),
  PaperAndPen: require('./paperAndPen.png'),
  President: require('./president.png'),
  Skull: require('./skull.png'),
  StudentHat: require('./studentHat.png'),
  Study: require('./study.png'),
  Swipe: require('./swipe.png'),
  Time: require('./time.png'),
  Write: require('./write.png'),
  MaintenanceJson: require('./maintenance.json'),
};
