module.exports = {
  Airplane: require('./airplane.png'),
  Baseball: require('./baseball.png'),
  PaperAndPen: require('./paperAndPen.png'),
  FlashLeft: require('./flash_left.png'),
  FlashRight: require('./flash_right.png'),
  GraduationSpeech: require('./graduationSpeech.png'),
  Grind: require('./grind.png'),
  Loading: require('./loading.gif'),
  LoadingWhite: require('./loading-white.gif'),
  Logo: require('./logo.png'),
  Note: require('./note.png'),
  Notification: require('./notification.png'),
  Office: require('./office.png'),
  Pen: require('./pen.png'),
  People: require('./people.png'),
  President: require('./president.png'),
  Skull: require('./skull.png'),
  Star: require('./star.png'),
  StudentHat: require('./studentHat.png'),
  Study: require('./study.png'),
  StudyTime: require('./studyTime.png'),
  Swipe: require('./swipe.png'),
  Time: require('./time.png'),
  Write: require('./write.png'),
  Zebbu: require('./zebbu.png'),
  Zenny: require('./zenny.png'),
};
